/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.adm;

import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author Administrator
 */
public class ClaitonTree extends javax.swing.JPanel {

    ArrayList<modelRoot> root = new ArrayList<>();
    int y = 0;

    public ClaitonTree() {
        initComponents();
        y = lblRoot.getY() + 20;

        for (int i = 0; i < 10; i++) {
            addComp("item " + i, i);
        }
        addCompAt("dsds", 0);
        addCompAt("qqqqqqqqqqqqqqqqqqqqqqqqqq", 0);
        addCompAt("rrrrrrrrrrrrrrrrrrr", 0);
        
        addCompAt("dsds", 3);
        addCompAt("qqqqqqqqqqqqqqqqqqqqqqqqqq", 3);
        addCompAt("rrrrrrrrrrrrrrrrrrr", 3);
    }

    final void addComp(String texto, int i) {
        JLabel l1 = new JLabel();
        ArrayList<JLabel> t = new ArrayList<JLabel>();

        l1.setText(texto);
        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Images/sort_right_20px.png"))); // NOI18N
        l1.setBounds(lblRoot.getX() + 10, y, l1.getText().length() * 20, 20);
        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Images/sort_down_20px.png"))); // NOI18N
                for (int i = 0; i < root.size(); i++) {
                    if (root.get(i).jlabel.equals(l1)) {//1
                        int x = root.get(i).jlabel.getX() + 20;
                        int y = root.get(i).jlabel.getX() + 20;
                        int w = root.get(i).jlabel.getWidth();
                        int h = root.get(i).jlabel.getHeight();
                        for (int j = 0; j < root.get(i).lista.size(); j++) {
                            root.get(i).lista.get(j).setBounds(x, y, w, h);
                            jPanel1.add(root.get(i).lista.get(j));//2
                            y += 20;
                            jPanel1.updateUI();
                        }

                        int y1 = root.get(i).lista.get(root.get(i).lista.size() - 1).getY() + 20;
                        int w1 = root.get(i).lista.get(root.get(i).lista.size() - 1).getWidth();
                        int h1 = root.get(i).lista.get(root.get(i).lista.size() - 1).getHeight();

                        for (int k = root.get(i).index; k < root.size(); k++) {
                            if (!root.get(k).jlabel.equals(l1)) {//1
                                if (root.get(i).index>root.get(k).index) {
                                                                jPanel1.remove(root.get(k).jlabel);
                                }
                            }
                        }
                        for (int k = 0; k < root.size(); k++) {
                                  if (!root.get(k).jlabel.equals(l1)) {//1
                            root.get(k).jlabel.setBounds(root.get(k).jlabel.getX(), y1, w1, h1);
                            jPanel1.add(root.get(k).jlabel);}
                            y1 += 20;
                        }
                    }
                }
            }
        });
        root.add(new modelRoot(i, l1, t));
        y += 20;
        jPanel1.add(l1);
    }

    final void addCompAt(String texto, int i) {
        JLabel l1 = new JLabel();
        ArrayList<JLabel> t = new ArrayList<JLabel>();

        l1.setText(texto);
        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Images/sort_right_20px.png"))); // NOI18N
        l1.setBounds(root.get(i).jlabel.getX() + 10, root.get(i).jlabel.getY() + 20, l1.getText().length() * 20, 20);
        root.get(i).lista.add(l1);
        System.out.println("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRoot = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));

        lblRoot.setText("Root");
        lblRoot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRootMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRoot)
                .addContainerGap(389, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRoot)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblRootMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRootMouseClicked
        //Claiton lopes matavele info: LinkedIn: Quality and Reality
    }//GEN-LAST:event_lblRootMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblRoot;
    // End of variables declaration//GEN-END:variables
}

class modelRoot {

    int index;
    ArrayList<JLabel> lista;
    JLabel jlabel;

    modelRoot(int index, JLabel jlabel, ArrayList<JLabel> lista) {
        this.index = index;
        this.lista = lista;
        this.jlabel = jlabel;
    }
}
