/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.clientes;

import Dao.JpaUtil;
import bean.Carro;
import bean.Cliente;
import bean.Motorrista;
import controller.CriarContaController;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.KeyStroke;

/**
 *
 * @author Administrator
 */
public class CriarContaJDialog extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form NewOkCancelDialog1
     */
    public CriarContaJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        criarContaJpanel = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        LblSenha = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        pfSenha = new javax.swing.JPasswordField();
        jsUsuario = new javax.swing.JSeparator();
        jsSenha = new javax.swing.JSeparator();
        btnLogin = new javax.swing.JButton();
        jsTitulo = new javax.swing.JSeparator();
        lblTitulo = new javax.swing.JLabel();
        lblconfirmarSenha = new javax.swing.JLabel();
        jsConfirmarSenha = new javax.swing.JSeparator();
        pfConfirmarSenha = new javax.swing.JPasswordField();
        lblFazerLogin = new javax.swing.JLabel();
        lblJaTemConta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        criarContaJpanel.setBackground(new java.awt.Color(245, 255, 252));
        criarContaJpanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        criarContaJpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setText("Usuario");
        criarContaJpanel.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 40, -1));

        LblSenha.setText("Senha");
        criarContaJpanel.add(LblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(245, 255, 252));
        txtUsuario.setBorder(null);
        txtUsuario.setOpaque(false);
        criarContaJpanel.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 220, 22));

        pfSenha.setBackground(new java.awt.Color(245, 255, 252));
        pfSenha.setBorder(null);
        criarContaJpanel.add(pfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 220, 20));
        criarContaJpanel.add(jsUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 220, -1));
        criarContaJpanel.add(jsSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 220, -1));

        btnLogin.setText("Criar  Conta");
        btnLogin.setBorder(null);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        criarContaJpanel.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 210, 20));
        criarContaJpanel.add(jsTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 52, 330, 10));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Criar Conta");
        criarContaJpanel.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 330, 30));

        lblconfirmarSenha.setText("Confirmar Senha");
        criarContaJpanel.add(lblconfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));
        criarContaJpanel.add(jsConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 220, -1));

        pfConfirmarSenha.setBackground(new java.awt.Color(245, 255, 252));
        pfConfirmarSenha.setBorder(null);
        criarContaJpanel.add(pfConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 220, 20));

        lblFazerLogin.setForeground(new java.awt.Color(102, 102, 255));
        lblFazerLogin.setText("Fazer Login");
        lblFazerLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFazerLoginMouseClicked(evt);
            }
        });
        criarContaJpanel.add(lblFazerLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        lblJaTemConta.setText("Ja tem conta?");
        criarContaJpanel.add(lblJaTemConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        jLabel1.setText("Criar conta como:");
        criarContaJpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jCheckBox1.setText("Cliente/Usuario Normal");
        criarContaJpanel.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jCheckBox2.setText("Imobiliario");
        criarContaJpanel.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jCheckBox4.setText("Motorrista");
        criarContaJpanel.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(criarContaJpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(criarContaJpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        new CriarContaController(this);
        doClose(RET_OK);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblFazerLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFazerLoginMouseClicked
        
        this.setVisible(false);
        new LoginJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_lblFazerLoginMouseClicked

    public JCheckBox getjCheckBox1() {
        return jCheckBox1;
    }

    public JCheckBox getjCheckBox2() {
        return jCheckBox2;
    }

    public JCheckBox getjCheckBox4() {
        return jCheckBox4;
    }

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    public JPasswordField getPfConfirmarSenha() {
        return pfConfirmarSenha;
    }

    public void setPfConfirmarSenha(JPasswordField pfConfirmarSenha) {
        this.pfConfirmarSenha = pfConfirmarSenha;
    }

    public JPasswordField getPfSenha() {
        return pfSenha;
    }

    public void setPfSenha(JPasswordField pfSenha) {
        this.pfSenha = pfSenha;
    }

    public JTextField getTxtUsuario() {
        return txtUsuario;
    }

    public void setTxtUsuario(JTextField txtUsuario) {
        this.txtUsuario = txtUsuario;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarContaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarContaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarContaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarContaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CriarContaJDialog dialog = new CriarContaJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblSenha;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel criarContaJpanel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jsConfirmarSenha;
    private javax.swing.JSeparator jsSenha;
    private javax.swing.JSeparator jsTitulo;
    private javax.swing.JSeparator jsUsuario;
    private javax.swing.JLabel lblFazerLogin;
    private javax.swing.JLabel lblJaTemConta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblconfirmarSenha;
    private javax.swing.JPasswordField pfConfirmarSenha;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
