/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.clientes;

import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JYearChooser;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author Administrator
 */
public class NewVeiculo extends javax.swing.JPanel {

    private boolean status = true;
    private int index;

    /**
     * Creates new form NewVeiculo
     */
    public NewVeiculo() {
        initComponents();
        btnGravar.setVisible(false);
        Component[] c1 = jPanel2Registo.getComponents();
        for (Component c : c1) {
            if (!(c instanceof JLabel)) {
                c.setEnabled(false);
            }

        }
    }

    public boolean isStatus() {
        return status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    public int getIndex() {
        return index;
    }

    public void setIndex(int index) {
        this.index = index;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2Registo = new javax.swing.JPanel();
        jLabelMarca = new javax.swing.JLabel();
        comboMarca = new javax.swing.JComboBox<>();
        jLabelModelo = new javax.swing.JLabel();
        comboModelo = new javax.swing.JComboBox<>();
        jLabelAcentos = new javax.swing.JLabel();
        spAcentos = new javax.swing.JSpinner();
        jLabelDataAqui = new javax.swing.JLabel();
        jLabelTonelagem = new javax.swing.JLabel();
        spTonelagem = new javax.swing.JSpinner();
        jLabelVeiculo = new javax.swing.JLabel();
        cbOnibus = new javax.swing.JCheckBox();
        cbTaxi = new javax.swing.JCheckBox();
        jLabelMotor = new javax.swing.JLabel();
        txtMotorAviao = new javax.swing.JTextField();
        jLabelMatricula = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        jLabelSerie = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        date = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        year = new com.toedter.calendar.JYearChooser();
        cbAtivo = new javax.swing.JCheckBox();
        lblDel = new javax.swing.JLabel();
        lblEdit = new javax.swing.JLabel();
        btnGravar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 51, 204));

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });

        jPanel2Registo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2RegistoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2RegistoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2RegistoMouseExited(evt);
            }
        });

        jLabelMarca.setText("Marca");

        comboMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelModelo.setText("Modelo");

        comboModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboModeloActionPerformed(evt);
            }
        });

        jLabelAcentos.setText("Cap Acentos");

        jLabelDataAqui.setText("Data de Aquisisao");

        jLabelTonelagem.setText("Cap Carga");

        jLabelVeiculo.setText("Veiculo");

        cbOnibus.setText("Onibus");

        cbTaxi.setText("Taxi");

        jLabelMotor.setText("Nr de Motor");

        jLabelMatricula.setText("Placa");

        txtMatricula.setText("              ");

        jLabelSerie.setText("Nr de Serie");

        txtSerie.setText("             ");
        txtSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerieActionPerformed(evt);
            }
        });

        jLabel3.setText("Ano");

        cbAtivo.setText("Ativo");

        lblDel.setText("del");
        lblDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDelMouseClicked(evt);
            }
        });

        lblEdit.setText("edit");
        lblEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2RegistoLayout = new javax.swing.GroupLayout(jPanel2Registo);
        jPanel2Registo.setLayout(jPanel2RegistoLayout);
        jPanel2RegistoLayout.setHorizontalGroup(
            jPanel2RegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2RegistoLayout.createSequentialGroup()
                .addGroup(jPanel2RegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2RegistoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cbOnibus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTaxi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2RegistoLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabelVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(37, 37, 37)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2RegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2RegistoLayout.createSequentialGroup()
                        .addComponent(jLabelMotor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(35, 35, 35))
                    .addComponent(txtMotorAviao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2RegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2RegistoLayout.createSequentialGroup()
                        .addComponent(jLabelSerie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(44, 44, 44))
                    .addComponent(txtSerie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2RegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2RegistoLayout.createSequentialGroup()
                        .addComponent(jLabelMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(114, 114, 114))
                    .addComponent(txtMatricula))
                .addGap(10, 10, 10)
                .addGroup(jPanel2RegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2RegistoLayout.createSequentialGroup()
                        .addComponent(jLabelMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27))
                    .addComponent(comboMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2RegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboModelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2RegistoLayout.createSequentialGroup()
                        .addComponent(jLabelModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2RegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2RegistoLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28))
                    .addComponent(year, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2RegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2RegistoLayout.createSequentialGroup()
                        .addComponent(jLabelAcentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addComponent(spAcentos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2RegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTonelagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spTonelagem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2RegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2RegistoLayout.createSequentialGroup()
                        .addComponent(jLabelDataAqui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(62, 62, 62))
                    .addGroup(jPanel2RegistoLayout.createSequentialGroup()
                        .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbAtivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2RegistoLayout.setVerticalGroup(
            jPanel2RegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2RegistoLayout.createSequentialGroup()
                .addGroup(jPanel2RegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2RegistoLayout.createSequentialGroup()
                        .addComponent(jLabelTonelagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2RegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spTonelagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spAcentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2RegistoLayout.createSequentialGroup()
                        .addComponent(jLabelVeiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2RegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbOnibus)
                            .addComponent(cbTaxi)))
                    .addGroup(jPanel2RegistoLayout.createSequentialGroup()
                        .addComponent(jLabelMotor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMotorAviao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2RegistoLayout.createSequentialGroup()
                        .addComponent(jLabelSerie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2RegistoLayout.createSequentialGroup()
                        .addComponent(jLabelMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2RegistoLayout.createSequentialGroup()
                        .addComponent(jLabelMatricula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelAcentos)
                    .addGroup(jPanel2RegistoLayout.createSequentialGroup()
                        .addGroup(jPanel2RegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelModelo)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2RegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(jPanel2RegistoLayout.createSequentialGroup()
                .addGroup(jPanel2RegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2RegistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbAtivo)
                        .addComponent(lblDel)
                        .addComponent(lblEdit))
                    .addGroup(jPanel2RegistoLayout.createSequentialGroup()
                        .addComponent(jLabelDataAqui)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnGravar.setText("Salvar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2Registo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGravar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2Registo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnGravar)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboModeloActionPerformed

    private void txtSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerieActionPerformed

    private void lblEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditMouseClicked
        Component[] c1 = jPanel2Registo.getComponents();
        for (Component c : c1) {
            c.setEnabled(true);
        }
        btnGravar.setVisible(true);
    }//GEN-LAST:event_lblEditMouseClicked

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        Component[] c1 = jPanel2Registo.getComponents();
        for (Component c : c1) {
            if (!(c instanceof JLabel)) {
                c.setEnabled(false);
            }
        }
        btnGravar.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_btnGravarActionPerformed

    private void lblDelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDelMouseClicked
//this.setVisible(false);
//getParent().setVisible(false);
        status = false;
    }//GEN-LAST:event_lblDelMouseClicked

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseExited

    private void jPanel2RegistoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2RegistoMouseClicked

    }//GEN-LAST:event_jPanel2RegistoMouseClicked

    private void jPanel2RegistoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2RegistoMouseExited
        jPanel1.setBackground(Color.blue);  // TODO add your handling code here:
        jPanel2Registo.setBackground(Color.blue);         // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2RegistoMouseExited

    private void jPanel2RegistoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2RegistoMouseEntered
        jPanel1.setBackground(Color.cyan); // TODO add your handling code here:
        jPanel2Registo.setBackground(Color.cyan);          // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2RegistoMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGravar;
    private javax.swing.JCheckBox cbAtivo;
    private javax.swing.JCheckBox cbOnibus;
    private javax.swing.JCheckBox cbTaxi;
    private javax.swing.JComboBox<String> comboMarca;
    private javax.swing.JComboBox<String> comboModelo;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAcentos;
    private javax.swing.JLabel jLabelDataAqui;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelMotor;
    private javax.swing.JLabel jLabelSerie;
    private javax.swing.JLabel jLabelTonelagem;
    private javax.swing.JLabel jLabelVeiculo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2Registo;
    private javax.swing.JLabel lblDel;
    private javax.swing.JLabel lblEdit;
    private javax.swing.JSpinner spAcentos;
    private javax.swing.JSpinner spTonelagem;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtMotorAviao;
    private javax.swing.JTextField txtSerie;
    private com.toedter.calendar.JYearChooser year;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnGravar() {
        return btnGravar;
    }

    public JCheckBox getCbAtivo() {
        return cbAtivo;
    }

    public JCheckBox getCbOnibus() {
        return cbOnibus;
    }

    public JCheckBox getCbTaxi() {
        return cbTaxi;
    }

    public JComboBox<String> getComboModelo() {
        return comboModelo;
    }

    public JDateChooser getDate() {
        return date;
    }

    public JLabel getLblDel() {
        return lblDel;
    }

    public JLabel getLblEdit() {
        return lblEdit;
    }

    public JSpinner getSpAcentos() {
        return spAcentos;
    }

    public JSpinner getSpTonelagem() {
        return spTonelagem;
    }

    public JTextField getTxtMatricula() {
        return txtMatricula;
    }

    public JTextField getTxtMotorAviao() {
        return txtMotorAviao;
    }

    public JTextField getTxtSerie() {
        return txtSerie;
    }

    public JYearChooser getYear() {
        return year;
    }

    public JComboBox<String> getComboMarca() {
        return comboMarca;
    }

}
