/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package claitonSwing;

import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class ClaitonRow extends javax.swing.JPanel {

    private JPanel jPanel;

    /**
     * Creates new form ClaitonColumm
     */
    public ClaitonRow() {
        initComponents();
    }
    public ClaitonRow(JPanel jPanel) {
        initComponents();
        this.jPanel =jPanel;
        add(jPanel);
        jPanel.setBounds(this.getBounds());
    }

    public void setjPanel(JPanel jPanel) {
        this.jPanel = jPanel;
    }

    public JPanel getjPanel() {
        return jPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(153, 51, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public Component getComponent(int i) {
        return super.getComponent(i); //To change body of generated methods, choose Tools | Templates.
    }
    public ClaitonColumm getComponent1(int i) {
        return (ClaitonColumm) super.getComponent(i); //To change body of generated methods, choose Tools | Templates.
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
